export type SearchRepoByKeywordsRes = {
  total_count: number;
  incomplete_results: boolean;
  items: [];
};

export type repoInfo = {
  id: 63477660;
  node_id: 'MDEwOlJlcG9zaXRvcnk2MzQ3NzY2MA==';
  name: 'Java';
  full_name: 'TheAlgorithms/Java';
  private: boolean;
  owner: {};
  html_url: 'https://github.com/TheAlgorithms/Java';
  description: 'All Algorithms implemented in Java';
  fork: boolean;
  url: 'https://api.github.com/repos/TheAlgorithms/Java';
  forks_url: 'https://api.github.com/repos/TheAlgorithms/Java/forks';
  keys_url: 'https://api.github.com/repos/TheAlgorithms/Java/keys{/key_id}';
  collaborators_url: 'https://api.github.com/repos/TheAlgorithms/Java/collaborators{/collaborator}';
  teams_url: 'https://api.github.com/repos/TheAlgorithms/Java/teams';
  hooks_url: 'https://api.github.com/repos/TheAlgorithms/Java/hooks';
  issue_events_url: 'https://api.github.com/repos/TheAlgorithms/Java/issues/events{/number}';
  events_url: 'https://api.github.com/repos/TheAlgorithms/Java/events';
  assignees_url: 'https://api.github.com/repos/TheAlgorithms/Java/assignees{/user}';
  branches_url: 'https://api.github.com/repos/TheAlgorithms/Java/branches{/branch}';
  tags_url: 'https://api.github.com/repos/TheAlgorithms/Java/tags';
  blobs_url: 'https://api.github.com/repos/TheAlgorithms/Java/git/blobs{/sha}';
  git_tags_url: 'https://api.github.com/repos/TheAlgorithms/Java/git/tags{/sha}';
  git_refs_url: 'https://api.github.com/repos/TheAlgorithms/Java/git/refs{/sha}';
  trees_url: 'https://api.github.com/repos/TheAlgorithms/Java/git/trees{/sha}';
  statuses_url: 'https://api.github.com/repos/TheAlgorithms/Java/statuses/{sha}';
  languages_url: 'https://api.github.com/repos/TheAlgorithms/Java/languages';
  stargazers_url: 'https://api.github.com/repos/TheAlgorithms/Java/stargazers';
  contributors_url: 'https://api.github.com/repos/TheAlgorithms/Java/contributors';
  subscribers_url: 'https://api.github.com/repos/TheAlgorithms/Java/subscribers';
  subscription_url: 'https://api.github.com/repos/TheAlgorithms/Java/subscription';
  commits_url: 'https://api.github.com/repos/TheAlgorithms/Java/commits{/sha}';
  git_commits_url: 'https://api.github.com/repos/TheAlgorithms/Java/git/commits{/sha}';
  comments_url: 'https://api.github.com/repos/TheAlgorithms/Java/comments{/number}';
  issue_comment_url: 'https://api.github.com/repos/TheAlgorithms/Java/issues/comments{/number}';
  contents_url: 'https://api.github.com/repos/TheAlgorithms/Java/contents/{+path}';
  compare_url: 'https://api.github.com/repos/TheAlgorithms/Java/compare/{base}...{head}';
  merges_url: 'https://api.github.com/repos/TheAlgorithms/Java/merges';
  archive_url: 'https://api.github.com/repos/TheAlgorithms/Java/{archive_format}{/ref}';
  downloads_url: 'https://api.github.com/repos/TheAlgorithms/Java/downloads';
  issues_url: 'https://api.github.com/repos/TheAlgorithms/Java/issues{/number}';
  pulls_url: 'https://api.github.com/repos/TheAlgorithms/Java/pulls{/number}';
  milestones_url: 'https://api.github.com/repos/TheAlgorithms/Java/milestones{/number}';
  notifications_url: 'https://api.github.com/repos/TheAlgorithms/Java/notifications{?since,all,participating}';
  labels_url: 'https://api.github.com/repos/TheAlgorithms/Java/labels{/name}';
  releases_url: 'https://api.github.com/repos/TheAlgorithms/Java/releases{/id}';
  deployments_url: 'https://api.github.com/repos/TheAlgorithms/Java/deployments';
  created_at: string;
  updated_at: string;
  pushed_at: string;
  git_url: string;
  ssh_url: string;
  clone_url: string;
  svn_url: string;
  homepage: string;
  size: number;
  stargazers_count: 46374;
  watchers_count: 46374;
  language: 'Java';
  has_issues: boolean;
  has_projects: boolean;
  has_downloads: boolean;
  has_wiki: boolean;
  has_pages: boolean;
  forks_count: number;
  mirror_url: string | null;
  archived: boolean;
  disabled: boolean;
  open_issues_count: number;
  license: {};
  allow_forking: boolean;
  is_template: boolean;
  topics: [];
  visibility: 'public' | 'private';
  forks: number;
  open_issues: number;
  watchers: number;
  default_branch: string;
  score: number;
};
